{
    "openapi": "3.0.0",
    "info": {
        "title": "Twitter API v2",
        "description": "Twitter API v2 available endpoints",
        "termsOfService": "https://developer.twitter.com/en/developer-terms/agreement-and-policy.html",
        "contact": {
            "name": "Twitter Developers",
            "url": "https://developer.twitter.com/2/"
        },
        "license": {
            "name": "Twitter Developer Agreement and Policy",
            "url": "https://developer.twitter.com/en/developer-terms/agreement-and-policy.html"
        },
        "version": "2.100"
    },
    "servers": [
        {
            "url": "https://api.twitter.com/2",
            "description": "Twitter API"
        }
    ],
    "tags": [
        {
            "name": "Bookmarks",
            "description": "Endpoints related to retrieving, managing bookmarks of a user"
        },
        {
            "name": "Compliance",
            "description": "Endpoints related to keeping X data in your systems compliant"
        },
        {
            "name": "Direct Messages",
            "description": "Endpoints related to retrieving, managing Direct Messages"
        },
        {
            "name": "General",
            "description": "Miscellaneous endpoints for general API functionality"
        },
        {
            "name": "Lists",
            "description": "Endpoints related to retrieving, managing Lists"
        },
        {
            "name": "Spaces",
            "description": "Endpoints related to retrieving, managing Spaces"
        },
        {
            "name": "Tweets",
            "description": "Endpoints related to retrieving, searching, and modifying Tweets"
        },
        {
            "name": "Users",
            "description": "Endpoints related to retrieving, managing relationships of Users"
        }
    ],
    "paths": {
        "/compliance/jobs": {
            "get": {
                "tags": [
                    "Compliance"
                ],
                "summary": "List Compliance Jobs",
                "description": "Returns recent Compliance Jobs for a given job type and optional job status",
                "operationId": "listBatchComplianceJobs",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Compliance"
                ],
                "summary": "Create compliance job",
                "description": "Creates a compliance for the given job type",
                "operationId": "createBatchComplianceJob",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/compliance/jobs/{id}": {
            "get": {
                "tags": [
                    "Compliance"
                ],
                "summary": "Get Compliance Job",
                "description": "Returns a single Compliance Job by ID",
                "operationId": "getBatchComplianceJob",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/dm_conversations": {
            "post": {
                "tags": [
                    "Direct Messages"
                ],
                "summary": "Create a new DM Conversation",
                "description": "Creates a new DM Conversation.",
                "operationId": "dmConversationIdCreate",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "dm.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/dm_conversations/with/{participantId}/dm_events": {
            "get": {
                "tags": [
                    "Direct Messages"
                ],
                "summary": "Get DM Events for a DM Conversation",
                "description": "Returns DM Events for a DM Conversation",
                "operationId": "getDmConversationsWithParticipantIdDmEvents",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "dm.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/dm_conversations/with/{participantId}/messages": {
            "post": {
                "tags": [
                    "Direct Messages"
                ],
                "summary": "Send a new message to a user",
                "description": "Creates a new message for a DM Conversation with a participant user by ID",
                "operationId": "dmConversationWithUserEventIdCreate",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "dm.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/dm_conversations/{dmConversationId}/messages": {
            "post": {
                "tags": [
                    "Direct Messages"
                ],
                "summary": "Send a new message to a DM Conversation",
                "description": "Creates a new message for a DM Conversation specified by DM Conversation ID",
                "operationId": "dmConversationByIdEventIdCreate",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "dm.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/dm_conversations/{id}/dm_events": {
            "get": {
                "tags": [
                    "Direct Messages"
                ],
                "summary": "Get DM Events for a DM Conversation",
                "description": "Returns DM Events for a DM Conversation",
                "operationId": "getDmConversationsIdDmEvents",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "dm.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/dm_events": {
            "get": {
                "tags": [
                    "Direct Messages"
                ],
                "summary": "Get recent DM Events",
                "description": "Returns recent DM Events across DM conversations",
                "operationId": "getDmEvents",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "dm.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/dm_events/{eventId}": {
            "get": {
                "tags": [
                    "Direct Messages"
                ],
                "summary": "Get DM Events by id",
                "description": "Returns DM Events by event id.",
                "operationId": "getDmEventsById",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "dm.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Direct Messages"
                ],
                "summary": "Delete Dm",
                "description": "Delete a Dm Event that you own.",
                "operationId": "dmEventDelete",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "dm.read",
                            "dm.write"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/likes/compliance/stream": {
            "get": {
                "tags": [
                    "Compliance"
                ],
                "summary": "Likes Compliance stream",
                "description": "Streams 100% of compliance data for Users",
                "operationId": "getLikesComplianceStream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/likes/firehose/stream": {
            "get": {
                "tags": [
                    "Likes"
                ],
                "summary": "Likes Firehose stream",
                "description": "Streams 100% of public Likes.",
                "operationId": "likesFirehoseStream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/likes/sample10/stream": {
            "get": {
                "tags": [
                    "Likes"
                ],
                "summary": "Likes Sample 10 stream",
                "description": "Streams 10% of public Likes.",
                "operationId": "likesSample10Stream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/lists": {
            "post": {
                "tags": [
                    "Lists"
                ],
                "summary": "Create List",
                "description": "Creates a new List.",
                "operationId": "listIdCreate",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.read",
                            "list.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/lists/{id}": {
            "get": {
                "tags": [
                    "Lists"
                ],
                "summary": "List lookup by List ID.",
                "description": "Returns a List.",
                "operationId": "listIdGet",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "list.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Lists"
                ],
                "summary": "Update List.",
                "description": "Update a List that you own.",
                "operationId": "listIdUpdate",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Lists"
                ],
                "summary": "Delete List",
                "description": "Delete a List that you own.",
                "operationId": "listIdDelete",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/lists/{id}/followers": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns User objects that follow a List by the provided List ID",
                "description": "Returns a list of Users that follow a List by the provided List ID",
                "operationId": "listGetFollowers",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "list.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/lists/{id}/members": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns User objects that are members of a List by the provided List ID.",
                "description": "Returns a list of Users that are members of a List by the provided List ID.",
                "operationId": "listGetMembers",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "list.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Lists"
                ],
                "summary": "Add a List member",
                "description": "Causes a User to become a member of a List.",
                "operationId": "listAddMember",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/lists/{id}/members/{userId}": {
            "delete": {
                "tags": [
                    "Lists"
                ],
                "summary": "Remove a List member",
                "description": "Causes a User to be removed from the members of a List.",
                "operationId": "listRemoveMember",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/lists/{id}/tweets": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "List Posts timeline by List ID.",
                "description": "Returns a list of Posts associated with the provided List ID.",
                "operationId": "listsIdTweets",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "list.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/openapi.json": {
            "get": {
                "tags": [
                    "General"
                ],
                "summary": "Returns the OpenAPI Specification document.",
                "description": "Full OpenAPI Specification in JSON format. (See https://github.com/OAI/OpenAPI-Specification/blob/master/README.md)",
                "operationId": "getOpenApiSpec"
            }
        },
        "/spaces": {
            "get": {
                "tags": [
                    "Spaces"
                ],
                "summary": "Space lookup up Space IDs",
                "description": "Returns a variety of information about the Spaces specified by the requested IDs",
                "operationId": "findSpacesByIds",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "space.read",
                            "tweet.read",
                            "users.read"
                        ]
                    }
                ]
            }
        },
        "/spaces/by/creator_ids": {
            "get": {
                "tags": [
                    "Spaces"
                ],
                "summary": "Space lookup by their creators",
                "description": "Returns a variety of information about the Spaces created by the provided User IDs",
                "operationId": "findSpacesByCreatorIds",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "space.read",
                            "tweet.read",
                            "users.read"
                        ]
                    }
                ]
            }
        },
        "/spaces/search": {
            "get": {
                "tags": [
                    "Spaces"
                ],
                "summary": "Search for Spaces",
                "description": "Returns Spaces that match the provided query.",
                "operationId": "searchSpaces",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "space.read",
                            "tweet.read",
                            "users.read"
                        ]
                    }
                ]
            }
        },
        "/spaces/{id}": {
            "get": {
                "tags": [
                    "Spaces"
                ],
                "summary": "Space lookup by Space ID",
                "description": "Returns a variety of information about the Space specified by the requested ID",
                "operationId": "findSpaceById",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "space.read",
                            "tweet.read",
                            "users.read"
                        ]
                    }
                ]
            }
        },
        "/spaces/{id}/buyers": {
            "get": {
                "tags": [
                    "Spaces",
                    "Tweets"
                ],
                "summary": "Retrieve the list of Users who purchased a ticket to the given space",
                "description": "Retrieves the list of Users who purchased a ticket to the given space",
                "operationId": "spaceBuyers",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "space.read",
                            "tweet.read",
                            "users.read"
                        ]
                    }
                ]
            }
        },
        "/spaces/{id}/tweets": {
            "get": {
                "tags": [
                    "Spaces",
                    "Tweets"
                ],
                "summary": "Retrieve Posts from a Space.",
                "description": "Retrieves Posts shared in the specified Space.",
                "operationId": "spaceTweets",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "space.read",
                            "tweet.read",
                            "users.read"
                        ]
                    }
                ]
            }
        },
        "/trends/by/woeid/{woeid}": {
            "get": {
                "tags": [
                    "Trends"
                ],
                "summary": "Trends",
                "description": "Returns the Trend associated with the supplied WoeId.",
                "operationId": "getTrends",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/tweets": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Post lookup by Post IDs",
                "description": "Returns a variety of information about the Post specified by the requested ID.",
                "operationId": "findTweetsById",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Creation of a Post",
                "description": "Causes the User to create a Post under the authorized account.",
                "operationId": "createTweet",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "tweet.write",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/tweets/compliance/stream": {
            "get": {
                "tags": [
                    "Compliance"
                ],
                "summary": "Posts Compliance stream",
                "description": "Streams 100% of compliance data for Posts",
                "operationId": "getTweetsComplianceStream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/counts/all": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Full archive search counts",
                "description": "Returns Post Counts that match a search query.",
                "operationId": "tweetCountsFullArchiveSearch",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/tweets/counts/recent": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Recent search counts",
                "description": "Returns Post Counts from the last 7 days that match a search query.",
                "operationId": "tweetCountsRecentSearch",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/tweets/firehose/stream": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Firehose stream",
                "description": "Streams 100% of public Posts.",
                "operationId": "getTweetsFirehoseStream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/firehose/stream/lang/en": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "English Language Firehose stream",
                "description": "Streams 100% of English Language public Posts.",
                "operationId": "getTweetsFirehoseStreamLangEn",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/firehose/stream/lang/ja": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Japanese Language Firehose stream",
                "description": "Streams 100% of Japanese Language public Posts.",
                "operationId": "getTweetsFirehoseStreamLangJa",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/firehose/stream/lang/ko": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Korean Language Firehose stream",
                "description": "Streams 100% of Korean Language public Posts.",
                "operationId": "getTweetsFirehoseStreamLangKo",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/firehose/stream/lang/pt": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Portuguese Language Firehose stream",
                "description": "Streams 100% of Portuguese Language public Posts.",
                "operationId": "getTweetsFirehoseStreamLangPt",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/label/stream": {
            "get": {
                "tags": [
                    "Compliance"
                ],
                "summary": "Posts Label stream",
                "description": "Streams 100% of labeling events applied to Posts",
                "operationId": "getTweetsLabelStream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/sample/stream": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Sample stream",
                "description": "Streams a deterministic 1% of public Posts.",
                "operationId": "sampleStream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/sample10/stream": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Sample 10% stream",
                "description": "Streams a deterministic 10% of public Posts.",
                "operationId": "getTweetsSample10Stream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/search/all": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Full-archive search",
                "description": "Returns Posts that match a search query.",
                "operationId": "tweetsFullarchiveSearch",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/tweets/search/recent": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Recent search",
                "description": "Returns Posts from the last 7 days that match a search query.",
                "operationId": "tweetsRecentSearch",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/tweets/search/stream": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Filtered stream",
                "description": "Streams Posts matching the stream's active rule set.",
                "operationId": "searchStream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/tweets/search/stream/rules": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Rules lookup",
                "description": "Returns rules from a User's active rule set. Users can fetch all of their rules or a subset, specified by the provided rule ids.",
                "operationId": "getRules",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Add/Delete rules",
                "description": "Add or delete rules from a User's active rule set. Users can provide unique, optionally tagged rules to add. Users can delete their entire rule set or a subset specified by rule ids or values.",
                "operationId": "addOrDeleteRules",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/tweets/search/stream/rules/counts": {
            "get": {
                "tags": [
                    "General"
                ],
                "summary": "Rules Count",
                "description": "Returns the counts of rules from a User's active rule set, to reflect usage by project and application.",
                "operationId": "getRuleCount",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/tweets/{id}": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Post lookup by Post ID",
                "description": "Returns a variety of information about the Post specified by the requested ID.",
                "operationId": "findTweetById",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Post delete by Post ID",
                "description": "Delete specified Post (in the path) by ID.",
                "operationId": "deleteTweetById",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "tweet.write",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/tweets/{id}/liking_users": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns User objects that have liked the provided Post ID",
                "description": "Returns a list of Users that have liked the provided Post ID",
                "operationId": "tweetsIdLikingUsers",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "like.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/tweets/{id}/quote_tweets": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Retrieve Posts that quote a Post.",
                "description": "Returns a variety of information about each Post that quotes the Post specified by the requested ID.",
                "operationId": "findTweetsThatQuoteATweet",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/tweets/{id}/retweeted_by": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns User objects that have retweeted the provided Post ID",
                "description": "Returns a list of Users that have retweeted the provided Post ID",
                "operationId": "tweetsIdRetweetingUsers",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/tweets/{id}/retweets": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Retrieve Posts that repost a Post.",
                "description": "Returns a variety of information about each Post that has retweeted the Post specified by the requested ID.",
                "operationId": "findTweetsThatRetweetATweet",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/tweets/{tweetId}/hidden": {
            "put": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Hide replies",
                "description": "Hides or unhides a reply to an owned conversation.",
                "operationId": "hideReplyById",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "tweet.moderate.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/usage/tweets": {
            "get": {
                "tags": [
                    "Usage"
                ],
                "summary": "Post Usage",
                "description": "Returns the Post Usage.",
                "operationId": "getUsageTweets",
                "security": [
                    {
                        "BearerToken": []
                    }
                ]
            }
        },
        "/users": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "User lookup by IDs",
                "description": "This endpoint returns information about Users. Specify Users by their ID.",
                "operationId": "findUsersById",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/by": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "User lookup by usernames",
                "description": "This endpoint returns information about Users. Specify Users by their username.",
                "operationId": "findUsersByUsername",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/by/username/{username}": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "User lookup by username",
                "description": "This endpoint returns information about a User. Specify User by username.",
                "operationId": "findUserByUsername",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/compliance/stream": {
            "get": {
                "tags": [
                    "Compliance"
                ],
                "summary": "Users Compliance stream",
                "description": "Streams 100% of compliance data for Users",
                "operationId": "getUsersComplianceStream",
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "x-twitter-streaming": true
            }
        },
        "/users/me": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "User lookup me",
                "description": "This endpoint returns information about the requesting User.",
                "operationId": "findMyUser",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/search": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "User search",
                "description": "Returns Users that match a search query.",
                "operationId": "searchUserByQuery",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "User lookup by ID",
                "description": "This endpoint returns information about a User. Specify User by ID.",
                "operationId": "findUserById",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/blocking": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns User objects that are blocked by provided User ID",
                "description": "Returns a list of Users that are blocked by the provided User ID",
                "operationId": "usersIdBlocking",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "block.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/bookmarks": {
            "get": {
                "tags": [
                    "Bookmarks"
                ],
                "summary": "Bookmarks by User",
                "description": "Returns Post objects that have been bookmarked by the requesting User",
                "operationId": "getUsersIdBookmarks",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "bookmark.read",
                            "tweet.read",
                            "users.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Bookmarks"
                ],
                "summary": "Add Post to Bookmarks",
                "description": "Adds a Post (ID in the body) to the requesting User's (in the path) bookmarks",
                "operationId": "postUsersIdBookmarks",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "bookmark.write",
                            "tweet.read",
                            "users.read"
                        ]
                    }
                ]
            }
        },
        "/users/{id}/bookmarks/{tweetId}": {
            "delete": {
                "tags": [
                    "Bookmarks"
                ],
                "summary": "Remove a bookmarked Post",
                "description": "Removes a Post from the requesting User's bookmarked Posts.",
                "operationId": "usersIdBookmarksDelete",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "bookmark.write",
                            "tweet.read",
                            "users.read"
                        ]
                    }
                ]
            }
        },
        "/users/{id}/followed_lists": {
            "get": {
                "tags": [
                    "Lists"
                ],
                "summary": "Get User's Followed Lists",
                "description": "Returns a User's followed Lists.",
                "operationId": "userFollowedLists",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "list.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Lists"
                ],
                "summary": "Follow a List",
                "description": "Causes a User to follow a List.",
                "operationId": "listUserFollow",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/followed_lists/{listId}": {
            "delete": {
                "tags": [
                    "Lists"
                ],
                "summary": "Unfollow a List",
                "description": "Causes a User to unfollow a List.",
                "operationId": "listUserUnfollow",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/followers": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Followers by User ID",
                "description": "Returns a list of Users who are followers of the specified User ID.",
                "operationId": "usersIdFollowers",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "follows.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/following": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Following by User ID",
                "description": "Returns a list of Users that are being followed by the provided User ID",
                "operationId": "usersIdFollowing",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "follows.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Follow User",
                "description": "Causes the User(in the path) to follow, or “request to follow” for protected Users, the target User. The User(in the path) must match the User context authorizing the request",
                "operationId": "usersIdFollow",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "follows.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/liked_tweets": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Returns Post objects liked by the provided User ID",
                "description": "Returns a list of Posts liked by the provided User ID",
                "operationId": "usersIdLikedTweets",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "like.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/likes": {
            "post": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Causes the User (in the path) to like the specified Post",
                "description": "Causes the User (in the path) to like the specified Post. The User in the path must match the User context authorizing the request.",
                "operationId": "usersIdLike",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "like.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/likes/{tweetId}": {
            "delete": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Causes the User (in the path) to unlike the specified Post",
                "description": "Causes the User (in the path) to unlike the specified Post. The User must match the User context authorizing the request",
                "operationId": "usersIdUnlike",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "like.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/list_memberships": {
            "get": {
                "tags": [
                    "Lists"
                ],
                "summary": "Get a User's List Memberships",
                "description": "Get a User's List Memberships.",
                "operationId": "getUserListMemberships",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "list.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/mentions": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "User mention timeline by User ID",
                "description": "Returns Post objects that mention username associated to the provided User ID",
                "operationId": "usersIdMentions",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/muting": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns User objects that are muted by the provided User ID",
                "description": "Returns a list of Users that are muted by the provided User ID",
                "operationId": "usersIdMuting",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "mute.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Mute User by User ID.",
                "description": "Causes the User (in the path) to mute the target User. The User (in the path) must match the User context authorizing the request.",
                "operationId": "usersIdMute",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "mute.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/owned_lists": {
            "get": {
                "tags": [
                    "Lists"
                ],
                "summary": "Get a User's Owned Lists.",
                "description": "Get a User's Owned Lists.",
                "operationId": "listUserOwnedLists",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "list.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/pinned_lists": {
            "get": {
                "tags": [
                    "Lists"
                ],
                "summary": "Get a User's Pinned Lists",
                "description": "Get a User's Pinned Lists.",
                "operationId": "listUserPinnedLists",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.read",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Lists"
                ],
                "summary": "Pin a List",
                "description": "Causes a User to pin a List.",
                "operationId": "listUserPin",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/pinned_lists/{listId}": {
            "delete": {
                "tags": [
                    "Lists"
                ],
                "summary": "Unpin a List",
                "description": "Causes a User to remove a pinned List.",
                "operationId": "listUserUnpin",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "list.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/retweets": {
            "post": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Causes the User (in the path) to repost the specified Post.",
                "description": "Causes the User (in the path) to repost the specified Post. The User in the path must match the User context authorizing the request.",
                "operationId": "usersIdRetweets",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "tweet.write",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/retweets/{sourceTweetId}": {
            "delete": {
                "tags": [
                    "Tweets"
                ],
                "summary": "Causes the User (in the path) to unretweet the specified Post",
                "description": "Causes the User (in the path) to unretweet the specified Post. The User must match the User context authorizing the request",
                "operationId": "usersIdUnretweets",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "tweet.write",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/timelines/reverse_chronological": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "User home timeline by User ID",
                "description": "Returns Post objects that appears in the provided User ID's home timeline",
                "operationId": "usersIdTimeline",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{id}/tweets": {
            "get": {
                "tags": [
                    "Tweets"
                ],
                "summary": "User Posts timeline by User ID",
                "description": "Returns a list of Posts authored by the provided User ID",
                "operationId": "usersIdTweets",
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "OAuth2UserToken": [
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{sourceUserId}/following/{targetUserId}": {
            "delete": {
                "tags": [
                    "Users"
                ],
                "summary": "Unfollow User",
                "description": "Causes the source User to unfollow the target User. The source User must match the User context authorizing the request",
                "operationId": "usersIdUnfollow",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "follows.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        },
        "/users/{sourceUserId}/muting/{targetUserId}": {
            "delete": {
                "tags": [
                    "Users"
                ],
                "summary": "Unmute User by User ID",
                "description": "Causes the source User to unmute the target User. The source User must match the User context authorizing the request",
                "operationId": "usersIdUnmute",
                "security": [
                    {
                        "OAuth2UserToken": [
                            "mute.write",
                            "tweet.read",
                            "users.read"
                        ]
                    },
                    {
                        "UserToken": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "BearerToken": {
                "type": "http",
                "scheme": "bearer"
            },
            "OAuth2UserToken": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://api.twitter.com/2/oauth2/authorize",
                        "tokenUrl": "https://api.twitter.com/2/oauth2/token",
                        "scopes": {
                            "block.read": "Accounts you’ve blocked.",
                            "bookmark.read": "Allows an app to read bookmarked Tweets",
                            "bookmark.write": "Allows an app to create and delete bookmarks",
                            "dm.read": "All your Direct Messages",
                            "dm.write": "Send and manage Direct Messages for you",
                            "follows.read": "People who follow you and people who you follow.",
                            "follows.write": "Follow and unfollow people for you.",
                            "like.read": "Tweets you’ve liked and likes you can view.",
                            "like.write": "Like and un-like Tweets for you.",
                            "list.read": "Lists, list members, and list followers of lists you’ve created or are a member of, including private lists.",
                            "list.write": "Create and manage Lists for you.",
                            "mute.read": "Accounts you’ve muted.",
                            "mute.write": "Mute and unmute accounts for you.",
                            "offline.access": "App can request refresh token.",
                            "space.read": "Access all of the Spaces you can see.",
                            "tweet.moderate.write": "Hide and unhide replies to your Tweets.",
                            "tweet.read": "All the Tweets you can see, including Tweets from protected accounts.",
                            "tweet.write": "Tweet and retweet for you.",
                            "users.read": "Any account you can see, including protected accounts. Any account you can see, including protected accounts."
                        }
                    }
                }
            },
            "UserToken": {
                "type": "http",
                "scheme": "OAuth"
            }
        }
    }
}